
set(CMAKE_CROSSCOMPILING 1)

set(CMAKE_TRY_COMPILE_TARGET_TYPE "STATIC_LIBRARY")

set(CMAKE_SYSTEM_NAME Linux)

set(LTOS_PROCESSOR_TARGET i686-pc-linux-gnu)
set(LTOS_LINKER "ld.lld")
set(LTOS_FIRMWARE_TARGET "PC")
set(LTOS_FIRMWARE_BOOTLOADER_PROTOCOL "MULTIBOOT1")

set(CMAKE_SYSTEM_PROCESSOR i686)
set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_ASM_COMPILER clang)

set(CMAKE_C_COMPILER_TARGET ${LTOS_PROCESSOR_TARGET})
set(CMAKE_CXX_COMPILER_TARGET ${LTOS_PROCESSOR_TARGET})
set(CMAKE_ASM_FLAGS "${CMAKE_ASM_FLAGS} -target ${LTOS_PROCESSOR_TARGET}")
#set(CMAKE_ASM_COMPILER_TARGET ${TARGET}) Hackfix! This not set target!

set(LINKING_FLAGS -nostdlib -fuse-ld=lld)
set(KERNEL_LINK_FLAGS ${LINKING_FLAGS} -fno-plt -fno-pic -Wl,--no-pie)
set(LOADER_LINK_FLAGS ${LINKING_FLAGS} -Wl,--no-pie)

set(CLANG_ERROR_FLAGS -Wno-vla)
set(COMPILING_FLAGS ${CLANG_ERROR_FLAGS} -ffreestanding -Wextra -Wall -Wpedantic -Wfatal-errors -O0 -g -mno-sse -fshort-wchar)

add_compile_options(${COMPILING_FLAGS})






